# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# platform :ios do
#   desc "Generate new localized screenshots"
#   lane :ios_beta_app do
#     capture_screenshots(workspace: "Runner.xcworkspace", scheme: "Runner")
#     build_app(
#       skip_build_archive: true,
#       archive_path: "../build/ios/archive/Runner.xcarchive",
#     )
#     upload_to_testflight
    
#   end
# end

platform :ios do
  desc "New iOS build for Counter Demo app"
    lane :ios_beta_app do
        build_app(
            scheme: "Runner",
            archive_path: "./build/Runner.xcarchive",
            export_method: "development",
            output_directory: "./build/Runner"
        )
        firebase_app_distribution(
            app: "1:521623137589:ios:582d38edce7708f74b707c",
            testers: "wilaiwan.k@assuretechnology.io,nnww9978@gmail.com",
            release_notes: "Initial test version of the app",
            firebase_cli_path: "/usr/local/bin/firebase",
            ipa_path: "./build/Runner/Runner.ipa"
        )
    end
end
